### ISSUE TITLE
大神请教一下系统安装

### ISSUE THREAD

**Issue by nattygui** [stevenliuit/Hackintosh-Intel-i7-10700k-ASUS-Z490m-plus-5500xt#1]
电脑配置基本相同，就是显卡使用的是rx 570 网卡使用的是dw1820a，我该如何设置才能正常安装？

**Comment by nattygui** [comment]
使用的是config_Igpu_only.plist, 一直卡在这里
![image](https://user-images.githubusercontent.com/38626036/107033121-cf6ffe00-67ef-11eb-8335-4977c72a0377.png)

**Comment by stevenliuit** [comment]
你可以先把网卡拔掉 然后bios改了吗？

**Comment by nattygui** [comment]
感谢回复！确实是网卡的问题，将网卡禁用后就可以了。
但是系统安装后 无限网卡一直安装不上！能请教下无限网卡需要设置什么吗？
我的无限网卡现在是使用另一块显卡槽拓展minipcie 接dw1820A，按照AirPortBrcmFixup驱动也已开启。但是开机的时候还是会出现上面的状况。

**Comment by stevenliuit** [comment]
这个问题不太清楚了 如果没猜错 你得屏蔽针脚才可以 建议还是用bcm的网卡

**Comment by nattygui** [comment]
暂时放弃了，dw1820a还是有点问题，感谢大佬的配置！！！
